<Project Sdk="Microsoft.NET.Sdk.Worker">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<UserSecretsId>dotnet-SMTPRouter.Service-18cfcd79-60cf-436a-93ac-2436d00660d9</UserSecretsId>

		<!-- Package Info -->
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<PackageId>SMTPRouter.Service</PackageId>
		<Version>0.1.0</Version>
		<Title>SMTP Router Service</Title>
		<Authors>Olavo Henrique Dias</Authors>
		<Company>Olavo Henrique Dias</Company>
		<Product>SMTPRouter</Product>
		<Description>A service to route messages from one SMTP to another</Description>
		<Summary>A service to route messages from one SMTP to another</Summary>
		<Copyright>Copyright © Olavo Henrique Dias 2025</Copyright>
		<NeutralLanguage>en-US</NeutralLanguage>
		<PackageTags>SMTP Router</PackageTags>
		<PackageReadmeFile>README.MD</PackageReadmeFile>
		<PackageIcon>packageIcon.png</PackageIcon>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<RootNamespace>SMTPRouter</RootNamespace>
		<AssemblyName>SMTPRouter.Service</AssemblyName>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="MailKit" Version="4.13.0" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
		<PackageReference Include="SmtpServer" Version="11.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Models\" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\SMTPRouter.Abstractions\SMTPRouter.Abstractions.csproj" />
	</ItemGroup>
</Project>
